Repository AWS-Cloud-School-6/AIWA-MCP-Backend-GcpService, pull requests merged in 2024-11, with the labels that each got.

#5 #4 Feat: Add StaticIp Describe
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  build/tmp/compileJava/compileTransaction/stash-dir/EipController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/GcpResourceService.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/SubnetController.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/VmController.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/VpcController.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/AIWA/McpBackend/controller/api/dto/staticip/StaticIpDto.java
  src/main/java/AIWA/McpBackend/controller/api/restcontroller/staticip/StaticIpController.java
  src/main/java/AIWA/McpBackend/service/gcp/GcpResourceService.java
  src/main/java/AIWA/McpBackend/service/gcp/s3/S3Service.java
  src/main/java/AIWA/McpBackend/service/terraform/TerraformService.java
Labels: enhancement

#7 #6 Feat: GCP Route Policy 조회 추가
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  build/tmp/compileJava/compileTransaction/stash-dir/GcpResourceService.class.uniqueId5
  build/tmp/compileJava/compileTransaction/stash-dir/RouteTableController.class.uniqueId6
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/AIWA/McpBackend/controller/api/dto/routetable/RoutePolicyDto.java
  src/main/java/AIWA/McpBackend/controller/api/restcontroller/routetable/RouteTableController.java
  src/main/java/AIWA/McpBackend/service/gcp/GcpResourceService.java
Labels: enhancement

#16 11 feat gcp resource
  .gradle/7.4/checksums/checksums.lock
  .gradle/7.4/checksums/md5-checksums.bin
  .gradle/7.4/checksums/sha1-checksums.bin
  .gradle/7.4/dependencies-accessors/dependencies-accessors.lock
  .gradle/7.4/dependencies-accessors/gc.properties
  .gradle/7.4/fileChanges/last-build.bin
  .gradle/7.4/fileHashes/fileHashes.lock
  .gradle/7.4/gc.properties
  .gradle/8.10.2/checksums/checksums.lock
  .gradle/8.10.2/checksums/md5-checksums.bin
  .gradle/8.10.2/checksums/sha1-checksums.bin
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .idea/modules/AIWA.McpBackend.main.iml
  .idea/modules/McpBackend.test.iml
  build.gradle
  build/tmp/compileJava/compileTransaction/stash-dir/TerraformService.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/VpcController.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/VpcService.class.uniqueId1
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/AIWA/McpBackend/config/s3/S3Config.java
  src/main/java/AIWA/McpBackend/controller/api/dto/vpc/VpcRequestDto.java
  src/main/java/AIWA/McpBackend/controller/api/restcontroller/vpc/VpcController.java
  src/main/java/AIWA/McpBackend/service/gcp/GcpResourceService.java
  src/main/java/AIWA/McpBackend/service/gcp/s3/S3Service.java
  src/main/java/AIWA/McpBackend/service/gcp/vpc/VpcService.java
  src/main/java/AIWA/McpBackend/service/response/ResponseService.java
  src/main/java/AIWA/McpBackend/service/terraform/TerraformService.java
Labels: enhancement

#21 #18 Feat: CloudMonitoring 생성 추가
  .gradle/8.10.2/executionHistory/executionHistory.bin
  .gradle/8.10.2/executionHistory/executionHistory.lock
  .gradle/8.10.2/fileHashes/fileHashes.bin
  .gradle/8.10.2/fileHashes/fileHashes.lock
  .gradle/8.10.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/AIWA/McpBackend/controller/api/restcontroller/cloudmonitoring/CloudMonitoringController.java
  src/main/java/AIWA/McpBackend/controller/api/restcontroller/cloudwatch/CloudWatchController.java
  src/main/java/AIWA/McpBackend/service/gcp/cloudmonitoring/CloudMonitoringService.java
Labels: enhancement

#22 20 feat routetable 생성 기능 추가
  src/main/java/AIWA/McpBackend/controller/api/dto/routetable/RouteTableRequestDto.java
  src/main/java/AIWA/McpBackend/controller/api/restcontroller/routetable/RouteTableController.java
  src/main/java/AIWA/McpBackend/service/gcp/GcpResourceService.java
  src/main/java/AIWA/McpBackend/service/gcp/routetable/RouteTableService.java
Labels: enhancement

#25 23 feat staticip 생성 기능 추가
  src/main/java/AIWA/McpBackend/controller/api/dto/staticip/StaticIpRequestDto.java
  src/main/java/AIWA/McpBackend/controller/api/restcontroller/staticip/StaticIpController.java
  src/main/java/AIWA/McpBackend/service/gcp/staticip/StaticIpService.java
Labels: enhancement

#27 26 feat vm 생성 기능 추가
  src/main/java/AIWA/McpBackend/controller/api/dto/vm/VmRequestDto.java
  src/main/java/AIWA/McpBackend/controller/api/restcontroller/vm/VmController.java
  src/main/java/AIWA/McpBackend/service/gcp/vm/VmService.java
Labels: enhancement

#28 #24 Cloud Nat 생성 추가
  src/main/java/AIWA/McpBackend/controller/api/dto/cloudnat/CloudNatRequestDto.java
  src/main/java/AIWA/McpBackend/controller/api/restcontroller/cloudnat/CloudNatController.java
  src/main/java/AIWA/McpBackend/service/gcp/cloudnat/CloudNatService.java
Labels: enhancement

#31 #29 Feat: FirewallPolicy -> Dto,Service,Controller 생성 완료 및 sg-> firew…
  src/main/java/AIWA/McpBackend/controller/api/dto/firewallpolicy/FireWallPolicyDto.java
  src/main/java/AIWA/McpBackend/controller/api/dto/firewallpolicy/FirewallPolicyRequestDto.java
  src/main/java/AIWA/McpBackend/controller/api/dto/securitygroup/SecurityGroupDTO.java
  src/main/java/AIWA/McpBackend/controller/api/dto/securitygroup/SecurityGroupRequestDto.java
  src/main/java/AIWA/McpBackend/controller/api/dto/securitygroup/SecurityGroupRuleDto.java
  src/main/java/AIWA/McpBackend/controller/api/restcontroller/firewallpolicy/FireWallPolicyController.java
  src/main/java/AIWA/McpBackend/service/gcp/GcpResourceService.java
  src/main/java/AIWA/McpBackend/service/gcp/firewallpolicy/FireWallPolicyService.java
Labels: enhancement

#33 #30 Feat: Cloud Router 생성 추가
  src/main/java/AIWA/McpBackend/controller/api/dto/cloudrouter/CloudRouterRequestDto.java
  src/main/java/AIWA/McpBackend/controller/api/restcontroller/cloudrouter/CloudRouterController.java
  src/main/java/AIWA/McpBackend/service/gcp/cloudnat/CloudNatService.java
  src/main/java/AIWA/McpBackend/service/gcp/cloudrouter/CloudRouterService.java
Labels: enhancement

#35 #32 Refac: AWS 서비스 삭제
  src/main/java/AIWA/McpBackend/controller/api/dto/ec2/Ec2InstanceDTO.java
  src/main/java/AIWA/McpBackend/controller/api/dto/ec2/Ec2RequestDto.java
  src/main/java/AIWA/McpBackend/controller/api/dto/eip/EipDto.java
  src/main/java/AIWA/McpBackend/controller/api/dto/eip/EipRequestDto.java
  src/main/java/AIWA/McpBackend/controller/api/dto/eni/NetworkInterfaceDto.java
  src/main/java/AIWA/McpBackend/controller/api/restcontroller/ec2/Ec2Controller.java
  src/main/java/AIWA/McpBackend/controller/api/restcontroller/eni/NetworkInterfaceController.java
  src/main/java/AIWA/McpBackend/service/gcp/ec2/Ec2Service.java
Labels: bug

#37 #36 Feat: Credential 경로 변경
  src/main/java/AIWA/McpBackend/controller/api/restcontroller/cloudnat/CloudNatController.java
  src/main/java/AIWA/McpBackend/controller/api/restcontroller/cloudrouter/CloudRouterController.java
  src/main/java/AIWA/McpBackend/controller/api/restcontroller/firewallpolicy/FireWallPolicyController.java
  src/main/java/AIWA/McpBackend/controller/api/restcontroller/routetable/RouteTableController.java
  src/main/java/AIWA/McpBackend/controller/api/restcontroller/staticip/StaticIpController.java
  src/main/java/AIWA/McpBackend/controller/api/restcontroller/subnet/SubnetController.java
  src/main/java/AIWA/McpBackend/controller/api/restcontroller/vm/VmController.java
  src/main/java/AIWA/McpBackend/controller/api/restcontroller/vpc/VpcController.java
  src/main/java/AIWA/McpBackend/service/gcp/GcpResourceService.java
  src/main/java/AIWA/McpBackend/service/gcp/s3/S3Service.java
Labels: enhancement

#39 #38 Fix: Credential 경로 수정
  src/main/java/AIWA/McpBackend/service/gcp/GcpResourceService.java
Labels: enhancement

#40 Fix: credential 경로 수정
  src/main/java/AIWA/McpBackend/service/gcp/GcpResourceService.java
Labels: Fix

#41 Fix: S3Service 의존성 주입
  src/main/java/AIWA/McpBackend/service/gcp/GcpResourceService.java
Labels: Fix
